### PR TITLE
Add support of protolock for ARM64 platform

### PR DESCRIPTION
**Pull request by liusheng**
When try to build other projects depend on protolock on ARM64 server, it will raise error:
```
OS not supported. Unable to find a protolock binary for the classifier linux-aarch_64
```
This change add a *protolock* binary for ARM64/aarch64 platform.

### CODE REVIEW

**Comment by liusheng** [comment]
Hi @rmichela ,
Could you please help to take a look this PR ?  Thank you.

**Comment by rmichela** [comment]
Where did you get the binary for arm64? There is no official protolock binary for that platform. https://github.com/nilslice/protolock/releases/tag/v0.15.0

**Review by rmichela — CHANGES_REQUESTED** [review]
Where did you get the binary for arm64? There is no official protolock binary for that platform. 

https://github.com/nilslice/protolock/releases/tag/v0.15.0

**Comment by liusheng** [comment]
> Where did you get the binary for arm64? There is no official protolock binary for that platform.
> 
> https://github.com/nilslice/protolock/releases/tag/v0.15.0

Sorry, I compiled the protolock binary on my ARM64 server, maybe need to firstly promote ARM64 release in protolock upstream ?

**Comment by rmichela** [comment]
> maybe need to firstly promote ARM64 release in protolock upstream

Yes. That's a good idea. 😄 While I like the idea of this PR, I can't accept an opaque binary that could do _literally anything_. Thank you for being understanding.

**Comment by liusheng** [comment]
Hi @rmichela , Thanks for your reply and suggestion, I have promoted protolock upstream to published a new `1.15.1` version including ARM64 binary, see: https://github.com/nilslice/protolock/releases/tag/v0.15.1
I will update this PR replace with the new arm64 binary, please take a look again.
Thank you.

**Comment by rmichela** [comment]
Perfect! Thank you.

**Comment by liusheng** [comment]
Hi @rmichela 
I have submitted the new `protolock` in https://github.com/salesforce/proto-backwards-compat-maven-plugin/pull/22
Thank you.

**Pull request closed without merging**
